### PR TITLE
Issue #91 - Log Exceptions in one line Log4j2

### PR DESCRIPTION
**Pull request by gala-lightfoot**
Throwables in the now log on one line in file appenders and stdout (pipe delimited).

one-line-log4j2-exceptions

### CODE REVIEW

**Review by gala-dan — DISMISSED** [review]
Looks good to me.

**Review by j-barber — DISMISSED** [review]
Does the pattern need to be updated in the standard log file (named RollingFileAppender) and also in the log4j-stdout.yml file?

**Comment by gala-lightfoot** [comment]
If we want this functionality on all logs, then yes.  I only added it to one FileAppender so it can act as an example.

**Comment by j-barber** [comment]
Would be best to clarify on the issue what the desired behavior is.

**Comment by hstandring** [comment]
My thought would be to include it everywhere.  Is there a benefit to having it log as a single line in some places and not in others?

Did you notice whether the exception was being logged twice after adding this or not?  Something I saw when I was playing with it was that the exception would get logged once on a single line and a second time spanning multiple lines.

**Review by GalateaRaj — COMMENTED** [review]
Should we have a Junit test for this?  I've always wondered that about logging.  Logging is an important part of every application, but we never seem to test that the output generated is as expected.

**Comment by gala-lightfoot** [comment]
@hstandring It's only being logged once from what I have seen so far (I'l keep an eye out now you've mentioned it).

Agreed.  It makes the most sense to me to use one line exception logging consistently with all logs.

We could have a high level test that verifies a defined output is contained within our logs after execution.  Interestingly something I've never seen done before (so maybe it's not just us!).

**Review by hstandring — APPROVED** [review]

**Pull request merged**
